<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="489.0130" tests="6" failures="5">
  <testsuite name="Root Suite" timestamp="2022-05-20T07:27:36" tests="0" file="cypress/integration/featuretest_editexistingtaxreturnform/021_editTaxReturn_IForm.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Edit Tax Return - IForm" timestamp="2022-05-20T07:27:36" tests="6" time="488.9880" failures="5">
    <testcase name="Edit Tax Return - IForm Edit Tax Return - IForm - Income - Salary and Gross Interest" time="0.0000" classname="Edit Tax Return - IForm - Income - Salary and Gross Interest">
      <failure message="The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.

  &gt; Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  &gt; `cy.wait()`

The cy command you invoked inside the promise was:

  &gt; `cy.log()`

Because Cypress commands are already promise-like, you don&apos;t need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

https://on.cypress.io/returning-promise-and-commands-in-another-command" type="CypressError"><![CDATA[CypressError: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > `cy.wait()`

The cy command you invoked inside the promise was:

  > `cy.log()`

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

https://on.cypress.io/returning-promise-and-commands-in-another-command
    at $Cy.cy.<computed> [as log] (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:178159:72)
From Your Spec Code:
    at Context.eval (https://htcqa.sagehandisoft.com.au/__cypress/tests?p=cypress\integration\featuretest_editexistingtaxreturnform\021_editTaxReturn_IForm.spec.js:19600:23)]]></failure>
    </testcase>
    <testcase name="Edit Tax Return - IForm Edit Tax Return - IForm - Income - Super Lump Sum" time="0.0000" classname="Edit Tax Return - IForm - Income - Super Lump Sum">
      <failure message="The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.

  &gt; Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  &gt; `cy.wait()`

The cy command you invoked inside the promise was:

  &gt; `cy.log()`

Because Cypress commands are already promise-like, you don&apos;t need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

https://on.cypress.io/returning-promise-and-commands-in-another-command" type="CypressError"><![CDATA[CypressError: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > `cy.wait()`

The cy command you invoked inside the promise was:

  > `cy.log()`

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

https://on.cypress.io/returning-promise-and-commands-in-another-command
    at $Cy.cy.<computed> [as log] (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:178159:72)
From Your Spec Code:
    at Context.eval (https://htcqa.sagehandisoft.com.au/__cypress/tests?p=cypress\integration\featuretest_editexistingtaxreturnform\021_editTaxReturn_IForm.spec.js:19600:23)]]></failure>
    </testcase>
    <testcase name="Edit Tax Return - IForm Edit Tax Return - IForm - Deduction" time="0.0000" classname="Edit Tax Return - IForm - Deduction">
      <failure message="The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.

  &gt; Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  &gt; `cy.wait()`

The cy command you invoked inside the promise was:

  &gt; `cy.log()`

Because Cypress commands are already promise-like, you don&apos;t need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

https://on.cypress.io/returning-promise-and-commands-in-another-command" type="CypressError"><![CDATA[CypressError: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > `cy.wait()`

The cy command you invoked inside the promise was:

  > `cy.log()`

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

https://on.cypress.io/returning-promise-and-commands-in-another-command
    at $Cy.cy.<computed> [as log] (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:178159:72)
From Your Spec Code:
    at Context.eval (https://htcqa.sagehandisoft.com.au/__cypress/tests?p=cypress\integration\featuretest_editexistingtaxreturnform\021_editTaxReturn_IForm.spec.js:19600:23)]]></failure>
    </testcase>
    <testcase name="Edit Tax Return - IForm Edit Tax Return - IForm - Tax Offset, Medicare and Adjustment" time="0.0000" classname="Edit Tax Return - IForm - Tax Offset, Medicare and Adjustment">
      <failure message="Timed out retrying after 30000ms: `cy.wait()` timed out waiting `30000ms` for the 1st response to the route: `afterSelectItem`. No response ever occurred.

https://on.cypress.io/wait" type="CypressError"><![CDATA[CypressError: Timed out retrying after 30000ms: `cy.wait()` timed out waiting `30000ms` for the 1st response to the route: `afterSelectItem`. No response ever occurred.

https://on.cypress.io/wait
    at cypressErr (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:181400:18)
    at Object.errByPath (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:181469:10)
    at checkForXhr (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:166631:92)
    at waitForResponse (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:166796:16)
From Your Spec Code:
    at CommonFunctions.searchAndLocateTheItemInTaxreturnForm (https://htcqa.sagehandisoft.com.au/__cypress/tests?p=cypress\integration\featuretest_editexistingtaxreturnform\021_editTaxReturn_IForm.spec.js:20303:8)
    at CommonFunctions.editTaxReturn_IForm_MedicareLevyRelatedItems (https://htcqa.sagehandisoft.com.au/__cypress/tests?p=cypress\integration\featuretest_editexistingtaxreturnform\021_editTaxReturn_IForm.spec.js:20312:10)
    at Context.eval (https://htcqa.sagehandisoft.com.au/__cypress/tests?p=cypress\integration\featuretest_editexistingtaxreturnform\021_editTaxReturn_IForm.spec.js:17807:21)]]></failure>
    </testcase>
    <testcase name="Edit Tax Return - IForm Edit Tax Return - IForm - Income Tests and Spouse Details" time="0.0000" classname="Edit Tax Return - IForm - Income Tests and Spouse Details">
      <failure message="Timed out retrying after 90000ms: `cy.clear()` failed because this element is detached from the DOM.

`&lt;input autocomplete=&quot;off&quot; class=&quot;dx-texteditor-input&quot; type=&quot;text&quot; spellcheck=&quot;false&quot; name=&quot;&quot; role=&quot;textbox&quot;&gt;`

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  &gt; `cy.xpath()`

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add &apos;guards&apos; which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom" type="CypressError"><![CDATA[CypressError: Timed out retrying after 90000ms: `cy.clear()` failed because this element is detached from the DOM.

`<input autocomplete="off" class="dx-texteditor-input" type="text" spellcheck="false" name="" role="textbox">`

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > `cy.xpath()`

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom
    at $Cy.ensureAttached (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:167985:76)
    at runAllChecks (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:154413:12)
    at retryActionability (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:154493:16)
    at tryCatcher (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:13022:23)
    at Function.Promise.attempt.Promise.try (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:10296:29)
    at whenStable (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:173538:65)
    at https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:172993:14
    at tryCatcher (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:11139:18)
    at Promise._fulfill (https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:11083:18)
    at https://htcqa.sagehandisoft.com.au/__cypress/runner/cypress_runner.js:12697:46
From Your Spec Code:
    at CommonFunctions.searchClient (https://htcqa.sagehandisoft.com.au/__cypress/tests?p=cypress\integration\featuretest_editexistingtaxreturnform\021_editTaxReturn_IForm.spec.js:18876:29)
    at CommonFunctions.displayTaxReturnForm (https://htcqa.sagehandisoft.com.au/__cypress/tests?p=cypress\integration\featuretest_editexistingtaxreturnform\021_editTaxReturn_IForm.spec.js:19481:10)
    at Context.eval (https://htcqa.sagehandisoft.com.au/__cypress/tests?p=cypress\integration\featuretest_editexistingtaxreturnform\021_editTaxReturn_IForm.spec.js:17821:21)]]></failure>
    </testcase>
    <testcase name="Edit Tax Return - IForm Edit Tax Return - IForm - Download and Validate Prefill Report" time="61.2520" classname="Edit Tax Return - IForm - Download and Validate Prefill Report">
    </testcase>
  </testsuite>
</testsuites>